### ISSUE TITLE
FSE & Block/Page Editor - Color palette/picker issues/enhancements

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2601]
This applies to FSE theme such as WordPress 2023 & 2022 Themes

- [x] **1. (Issue) FSE - If Stackable plugin is activated, color palette doesn't display default theme colors on FSE editor even if “Use only Stackable colors” is disabled** - https://github.com/gambitph/Stackable/issues/2599

- [x] **2. (Issue) If Custom color is added, Theme colors are missing in Stackable color picker**
	     - Happens if **Use only Stackable colors** is disabled
             - Missing in:
		- Global Color Palette
		- Stackable color picker
		- Native block color picker missing theme colors (post/page editor)
	  Expected: 
            - Stackable color picker should show: Theme colors, stackable global colors, and custom colors (post/page editor)
            - Native block color picker should show Theme colors on THEME and custom colors on CUSTOM
	    - Global Color Palette should show: Theme colors & custom colors (locked) and custom colors
	  Screenshots:
            https://user-images.githubusercontent.com/103395655/223603237-75b36c3f-dbc3-4218-9a61-a480e73f17c0.mp4

- [x] **3. (Issue) Default colors not reflecting for Stackable blocks when modified (FSE issue only)**
         See video: https://user-images.githubusercontent.com/103395655/223604893-ecd1bbe2-983e-40f8-8979-0b4d61868869.mp4

- [x] **4. (Enhancement) Add categories on Stackable's color picker** - https://github.com/gambitph/Stackable/issues/2600

- [x] **5. (Issue) FSE - Global Color Palette displays only Default colors. Theme & Custom colors are missing**
          - Theme color palette
![image](https://user-images.githubusercontent.com/103395655/226783104-60d69392-8795-4e93-85e8-0db7af2521de.png)
          - Global Color Palette
![image](https://user-images.githubusercontent.com/103395655/226783979-57ac5100-886b-4252-914d-df62811457e1.png)

- [ ] 6. **(Issue) When selecting a theme color from WordPress theme and switching style variation, Stackable block doesn't follow the color anymore** - https://github.com/gambitph/Stackable/issues/2639

- [x] 7. **(Issue) [Inconsistent] Colors doesn't show up in Color Palette**
      - Related to: https://secure.helpscout.net/conversation/2287582341/20887?folderId=2526706#modal
      - You have to toggle on/off the "use only stackable colors" for the colors to appear in the palette.
<img width="595" alt="Screenshot 2023-06-30 at 10 13 49 PM" src="https://github.com/gambitph/Stackable/assets/103395655/81ed913c-ff26-40dd-9fbc-730e65a77492">

https://github.com/gambitph/Stackable/assets/103395655/abc08ea5-b1ef-4d0f-9706-a5d8c118a0eb
