### ISSUE TITLE
[Meta Box] Some supported fields are showing an error when pulling content in a single template or content blocks

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#3156]
**Describe the bug**
- Upon pulling the field data, it shows as invalid type which I'm unable to proceed.
- Issue happens when creating custom template (any theme) / content blocks (Blocksy)
- This error also shows on Network tab > Response:
<img width="1675" alt="Screenshot 2024-04-17 at 12 15 49 PM" src="https://github.com/gambitph/Stackable/assets/103395655/033a106d-0484-4498-bb33-e6b3d1d5d663">

```
{
    "code": "internal_server_error",
    "message": "<p>There has been a critical error on this website.<\/p><p><a href=\"https:\/\/wordpress.org\/documentation\/article\/faq-troubleshooting\/\">Learn more about troubleshooting WordPress.<\/a><\/p>",
    "data": {
        "status": 500,
        "error": {
            "type": 1,
            "message": "Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, bool given in \/Users\/andrearollon\/Local Sites\/3rd-party-integration-testing\/app\/public\/wp-content\/plugins\/stackable-ultimate-gutenberg-blocks-premium\/pro__premium_only\/src\/dynamic-content\/sources\/metabox.php:493\nStack trace:\n#0 \/Users\/andrearollon\/Local Sites\/3rd-party-integration-testing\/app\/public\/wp-content\/plugins\/stackable-ultimate-gutenberg-blocks-premium\/pro__premium_only\/src\/dynamic-content\/sources\/metabox.php(493): implode(', ', false)\n#1 \/Users\/andrearollon\/Local Sites\/3rd-party-integration-testing\/app\/public\/wp-content\/plugins\/stackable-ultimate-gutenberg-blocks-premium\/pro__premium_only\/src\/dynamic-content\/sources\/metabox.php(276): Stackable\\DynamicContent\\Sources\\Metabox->render_checkbox(Array, true)\n#2 \/Users\/andrearollon\/Local Sites\/3rd-party-integration-testing\/app\/public\/wp-includes\/class-wp-hook.php(326): Stackable\\DynamicContent\\Sources\\Metabox->get_content(Array, Array, true)\n#3 \/Users\/andrearollon\/Local Sites\/3rd-party-integration-testing\/app\/public\/wp-includes\/plugin.php(205): WP_Hook->apply_filters(Array, Array)\n#4 \/Users\/andrearollon\/Local Sites\/3rd-party-integration-testing\/app\/public\/wp-content\/plugins\/stackable-ultimate-gutenberg-blocks-premium\/pro__premium_only\/src\/dynamic-content\/init.php(280): apply_filters('stackable_dynam...', NULL, Array, true, NULL, Array)\n#5 \/Users\/andrearollon\/Local Sites\/3rd-party-integration-testing\/app\/public\/wp-content\/plugins\/stackable-ultimate-gutenberg-blocks-premium\/pro__premium_only\/src\/dynamic-content\/init.php(307): Stackable\\DynamicContent\\Stackable_Dynamic_Content::get_dynamic_content('current-page\/an...', true, NULL, NULL, Array)\n#6 \/Users\/andrearollon\/Local Sites\/3rd-party-integration-testing\/app\/public\/wp-includes\/rest-api\/class-wp-rest-server.php(1230): Stackable\\DynamicContent\\Stackable_Dynamic_Content->get_content(Object(WP_REST_Request))\n#7 \/Users\/andrearollon\/Local Sites\/3rd-party-integration-testing\/app\/public\/wp-includes\/rest-api\/class-wp-rest-server.php(1063): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '\/stackable\/v3\/c...', Array, NULL)\n#8 \/Users\/andrearollon\/Local Sites\/3rd-party-integration-testing\/app\/public\/wp-includes\/rest-api\/class-wp-rest-server.php(439): WP_REST_Server->dispatch(Object(WP_REST_Request))\n#9 \/Users\/andrearollon\/Local Sites\/3rd-party-integration-testing\/app\/public\/wp-includes\/rest-api.php(428): WP_REST_Server->serve_request('\/stackable\/v3\/c...')\n#10 \/Users\/andrearollon\/Local Sites\/3rd-party-integration-testing\/app\/public\/wp-includes\/class-wp-hook.php(324): rest_api_loaded(Object(WP))\n#11 \/Users\/andrearollon\/Local Sites\/3rd-party-integration-testing\/app\/public\/wp-includes\/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#12 \/Users\/andrearollon\/Local Sites\/3rd-party-integration-testing\/app\/public\/wp-includes\/plugin.php(565): WP_Hook->do_action(Array)\n#13 \/Users\/andrearollon\/Local Sites\/3rd-party-integration-testing\/app\/public\/wp-includes\/class-wp.php(418): do_action_ref_array('parse_request', Array)\n#14 \/Users\/andrearollon\/Local Sites\/3rd-party-integration-testing\/app\/public\/wp-includes\/class-wp.php(813): WP->parse_request('')\n#15 \/Users\/andrearollon\/Local Sites\/3rd-party-integration-testing\/app\/public\/wp-includes\/functions.php(1336): WP->main('')\n#16 \/Users\/andrearollon\/Local Sites\/3rd-party-integration-testing\/app\/public\/wp-blog-header.php(16): wp()\n#17 \/Users\/andrearollon\/Local Sites\/3rd-party-integration-testing\/app\/public\/index.php(17): require('\/Users\/andrearo...')\n#18 {main}\n  thrown",
            "file": "\/Users\/andrearollon\/Local Sites\/3rd-party-integration-testing\/app\/public\/wp-content\/plugins\/stackable-ultimate-gutenberg-blocks-premium\/pro__premium_only\/src\/dynamic-content\/sources\/metabox.php",
            "line": 493
        }
    },
    "additional_errors": []
}
```
- Affects the ff. fields:
       - [ ] Checkbox List
       - [ ] Select
       - [ ] Select Advanced
       - [ ] Video
       - [ ] Autocomplete
       - [ ] Image Select (double check)
       - [ ] Taxonomy (double check)
       - [ ] Taxonomy Advanced  (double check)
       - [ ] File (double check)
       - [ ] File Advanced (double check)

**To Reproduce**
_**Blocksy Content Blocks**_
1. Add a new **Single Template** Content Block
2. Add a Heading block
3. Pull data from any of the fields mentioned above (e.g. Checkbox List)
4. See that it doesn't pull successfully
5. Inspect element and see Network tab
6. Open the Network name mentioned in the screenshot above
7. See the error

_**Single Template (Using Twenty Twenty Four theme)**_
1. Go to Appearance > Editor
2. Go to **Templates** and add a new template
3. Select **Custom Template**
4. Skip pattern
5. Add a Heading block
6. Pull data from any of the fields mentioned above (e.g. Checkbox List)
7. See that it doesn't pull successfully
8. Inspect element and see Network tab
9. Open the Network name mentioned in the screenshot above
10. See the error
 
**Expected behavior**
- All supported fields should not show an error when pulling content in a single template or content block

**Screenshots**
**Content Block**

https://github.com/gambitph/Stackable/assets/103395655/8b352cff-46b0-4d4c-a958-9219a7e31f2c

**Custom Template**

https://github.com/gambitph/Stackable/assets/103395655/7c133b67-7fe9-4ec5-9ef1-5bf3952edbcb
